#!/bin/sh

# Check to see if there is an agent running
if [ -S "$SSH_AUTH_SOCK" -a "$SSH_AGENT_PID" ] ; then 
	ssh-add -l &> /dev/null
	# ssh-add -l returns 1 if there are no keys loaded
	if [ $? -eq 1 ] ; then
		# So add one with a lifetime of an hour
		ssh-add -t 3600
	fi
fi
