#!/usr/bin/perl
use strict;
use warnings;
use File::Find;

my $walldir = "$ENV{HOME}/Dropbox/Photos/Wallpapers";
my @files;
find({ wanted => \&push_file, no_chdir => 1 }, $walldir);

my $index = int(rand(@files));
exec("DISPLAY=:0 feh --bg-scale $files[${index}]");

sub push_file
{
	push @files, $_ if -f $_;
}
