#!/bin/sh
#FreeDNS updater script

logfile=/var/log/freedns
updateurl="http://freedns.afraid.org/dynamic/update.php?VURyMkw2MzFVMVVBQUtrSTlhd0FBQUFFOjg5MjMzMzA="
domain="YOURDOMAINHERE"

registered=$(nslookup $domain|tail -n2|grep A|sed s/[^0-9.]//g)

current=$(wget -q -O - http://checkip.dyndns.org|sed s/[^0-9.]//g)
{
	if [ "$current" != "$registered" ] ; then
		wget -q -O /dev/null $updateurl 
		printf "$(date +"%Y-%m-%d %R:%S"):\tIP udated from $registered to $current\n"
	else
		printf "$(date +"%Y-%m-%d %R:%S"):\tRegistered IP matches current IP, no update\n"
	fi
} >>$logfile
