#!/bin/bash
dpkg -l 'linux-*' \
	| sed '/^ii/!d;/'"$(uname -r \
	| sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d' \
	| head -n -1 \
	| tail -n +3 \
	| xargs sudo apt-get -y purge
