#!/usr/bin/perl
use strict;
use warnings;
use Math::Cartesian::Product;
use List::Util qw{shuffle};
use Term::ReadKey;

my $parts = [qw (Noun Verb)];
my $cases = [qw (Nominative Genitive Accusative Dative Ablative Vocative)];
my $number = [qw (Singular Plural)];
my $tenses = [("Present", "Imperfect", "Future", "Perfect", "Pluperfect", "Future Perfect")];
my $moods = [qw (Indicative Subjunctive Imperative)];
my $persons = [qw (First Second Third)];
my $voices = [qw (Active Passive)];

my ($key, $response, @forms);

do
{
	while (1)
	{
		$response = listforms(@$parts);

		if ($response =~ m/^ve?r?b?$/i)
		{
			@forms = verbs();
			last;
		}
		elsif ($response =~ m/^no?u?n?$/i)
		{
			@forms = shuffle cartesian {1} $cases, $number;
			last;
		}
	}

	ReadMode 4;
	for (@forms)
	{
		print "@$_";
		while (not defined ($key = ReadKey(-1)))
		{
			# Essentially nop. Needs more nop.
			undef $key;
		}
		print"\n";
	}
	ReadMode 0;

	do
	{
		print "Again? (y/n): ";
		$response = <STDIN>;
	} while ($response !~ m/(ye?s?)|(no?)/i)
} while ($response =~ m/^ye?s?$/i);

sub listforms
{
	@forms = @_;
	print shift @forms;
	while (@forms)
	{
		printf " or %s", shift @forms;
	}
	print "? ";
	my $response = <STDIN>;
	return $response;
}

sub verbs
{
	my ($response, $selectedVoice, $selectedMood);
	
	# Get the desired mood
	while (1)
	{
		$response = listforms(@$moods);
		if ($response =~ m/^ind?i?c?a?t?i?v?e?$/i)
		{
			$selectedMood = [("Indicative")];
			last;
		}
		elsif ($response =~ m/^su?b?j?u?n?c?t?i?v?e?$/i)
		{
			$selectedMood = [("Subjunctive")];
			last;
		}
		elsif ($response =~ m/^imp?e?a?t?i?v?e?$/i)
		{
			$selectedMood = [("Imperative")];
			last;
		}
		elsif ($response =~ m/^all$/i)
		{
			$selectedMood = $moods;
			last;
		}
	}

	# Get the desired voice
	while (1)
	{
		$response = listforms(@$voices);
		if ($response =~ m/^act?i?v?e?$/i)
		{
			$selectedVoice = [("Active")];
			last;
		}
		elsif ($response =~ m/^pa?s?s?i?v?e?$/i)
		{
			$selectedVoice = [("Passive")];
			last;
		}
		elsif ($response =~ m/^all$/i)
		{
			$selectedVoice = $voices;
			last;
		}
	}

	# Return the cross product of the selected verb arrays
	return shuffle cartesian {1} $persons, $number, $tenses, $selectedVoice, $selectedMood;
}
