#!/bin/bash

if [ -t 1 ] ; then
	export MANROFFOPT="-c $MANROFFOPT"
	export MANPAGER="/bin/bash -c \"vim -nc 'set ft=man' </dev/tty <(col -b -x)\""
else
	export MANPAGER='less -s'
fi

/usr/bin/man "$@"
