#!/bin/bash
trap exit SIGINT SIGTSTP

host="$1"

if ping -c 1 -w 1 "$host" > /dev/null 2>&1 ; then
	printf 'Waiting for host %s to stop responding...' "$host"
	while true ; do
		ping -c 1 -w 1 "$host" > /dev/null 2>&1 || break
		echo -n .
		sleep 1
	done
	echo ''
fi

printf 'Host %s is down...' "$host"
while true ; do
	ping -c 1 -w 1 "$host" > /dev/null 2>&1 && break
	echo -n .
	sleep 1
done

printf '\nHost %s is up!\n' "$host"
