#!/bin/bash
trap exit SIGTERM SIGSTOP

host="$1"

if ping -c 1 -w 1 "$host" > /dev/null 2>&1 ; then
	printf 'Waiting for host %s to stop responding...\n' "$host"
	while true ; do
		ping -c 1 -w 1 "$host" > /dev/null 2>&1 || break
	done
	sleep 10
fi
printf 'Host %s is down...\n' "$host"

while true ; do
	ping -c 1 -w 1 "$host" > /dev/null 2>&1 && break
done
printf 'Host %s is up!\n' "$host"
