#!/usr/bin/perl
use strict;
use warnings;
use IO::Uncompress::Unzip qw(unzip $UnzipError);

my @zipfiles = glob("imgur_*.zip");

foreach my $archive (@zipfiles)
{
	printf "Processing $archive...\n";
	(my $prefix = $archive) =~ s/imgur_(.*)\.zip/$1/;

	my $unzip = new IO::Uncompress::Unzip $archive
		or die "Cannot open $archive: $UnzipError\n";

	die "Zip file has no headers"
		unless defined $unzip->getHeaderInfo;

	for (my $status = 1; $status > 0; $status = $unzip->nextStream)
	{
		my $src_file = $unzip->getHeaderInfo->{'Name'};
		
		unless ($src_file eq "log.txt")
		{
			my $dst_file = "$prefix-$src_file";
			my $fh = IO::File->new("$dst_file", "w");

			my $buff;
			while(($status = $unzip->read($buff)) > 0)
			{
				$fh->write($buff);
			}

			last if $status < 0 ;
		}
	}
	unlink("$archive");
	unlink("${prefix}-captions.txt");
	printf "Processing of $archive complete!\n";
}
