#!/bin/bash

# Vimdiff accepts 2, 3, or 4 files
if [ $# -lt 2 -o $# -gt 4 ] ; then
	echo "Invalid number of arguments"
	exit 1
fi

# Store the number of args
argc=$#

# Declare an array
files=()

# Check the arguemets
while (( $# )) ; do
	# We cannot see this file, bail
	if  [ ! -f "$1" ] ; then
		echo "Cannot open $1: no such file or directory"
		exit 2
	fi

	# We cannot read this file, bail
	if [ ! -r "$1" ] ; then 
		echo "Cannot open $1: permission denied"
		exit 3
	fi

	# Looks like this file is fine, add it to the array
	files+=("$1")

	# Next
	shift
done

# This seems oafish
case $argc in
	2)	vimdiff <(xxd "${files[0]}") <(xxd "${files[1]}")
		;;
	3)	vimdiff <(xxd "${files[0]}") <(xxd "${files[1]}") <(xxd "${files[2]}")
		;;
	4)	vimdiff <(xxd "${files[0]}") <(xxd "${files[1]}") <(xxd "${files[2]}") <(xxd "${files[3]}")
		;;
	*)	echo "I don't know how you got here, but something went wrong"
		exit 4
		;;
esac

# Exit with whatever vimdiff did
exit $?
