#!/bin/bash

me="$(basename "$(echo "$0")")"
rc="$HOME/.vimrc"
opts=( -n -c 'set ft=man' )
[ -r "$rc" ] && opts=( '-u' "$rc" "${opts[@]}")
export opts

if [ -t 1 ] ; then
	export MANROFFOPT="-c $MANROFFOPT"
	export MANPAGER="/bin/bash -c \"vim $(printf "'%s' " "${opts[@]}") </dev/tty <(col -b -x)\""
else
	export MANPAGER='less -s'
fi

exec "/usr/bin/$me" "$@"
