#!/bin/sh

# Detect what we were called as, e.g. view, vim, vimdiff
me="$(basename "$0")"
vim="/usr/bin/$me"

opts=()
if [ $UID -eq 0 ] && [ -r "$HOME/.vimrc" ] ; then
	vimrc="$HOME/.vimrc"
	export MYVIMRC="$vimrc"
		opts=( -u "$vimrc" )
fi
exec "$vim" "${opts[@]}" "$@"
